{% set name = "LbEnv" %}
{% set version = "2.1.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 04c99f74eb1cd3644d931aa410ac8ad70d7f32ccf32a323ee1531ac141da6a04

build:
  number: 0
  # Can't be noarch due to use of 2to3 in setup.py
  # noarch: python
  entry_points:
    - lb-run=LbEnv.ProjectEnv.script:main
    - lb-completion-helper=LbEnv.Utils.Completion:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - setuptools_scm <6                      # [build_platform != target_platform]
    - nose                                   # [build_platform != target_platform]
  host:
    - pip
    - python
    - setuptools_scm <6
    - nose
  run:
    - lbplatformutils >=4.2.3
    - python
    - setuptools
    - six
    - xenv <1.0.0

test:
  imports:
    - LbEnv
    - LbEnv.ProjectEnv
    - LbEnv.Utils
  commands:
    - lb-run --help
    - lb-completion-helper --help

about:
  home: https://gitlab.cern.ch/lhcb-core/LbEnv
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: LHCb Environment tools
  doc_url: https://gitlab.cern.ch/lhcb-core/LbEnv
  dev_url: https://gitlab.cern.ch/lhcb-core/LbEnv

extra:
  recipe-maintainers:
    - chrisburr
