travis:
  secure:
    BINSTAR_TOKEN: eyimbZb5PK7pRn96CNhsGjG+IUUWJPk2maqfINcUjqzFZt0dfJem3EgXZ64XOiwwR9U4Tl56ijqejVH7RFQgMrzT8akf759uy2m+YMwP9J+pwEp4mab9Wju1aTrLWfpdfKlO7RhYvrmkffiFqFavquPmf3tVkiM5cgxDmjulNkC+pwXIUerZD3rXsVMuUkWn8L4kh5GAP9d3AlB+1laaIyhoboWJ23gmDdb1jd+mc4zc3hmPfk9cAc2lQ6cnfbfbBjJhcuoUp5mff72Qzc/P00/N84EeNW0m8g9NOaLkslvFyXFIuI15x2pdoJK6RKpUGfGKZq7ydN77jOYX7fFHNeMdsBfbzZm2hH5qvhJpRxKbkPvJkOuEv8Bpy3+DQmx8sXpwIajATaw5wu4dJ6gZj/kkaaIvipm7OfnBERZ3ENrK52/QOJUl9CHxvBztOoVvPZUDLROZ90oFWY1u1RfzzTcEw7eRtFOWEdeIKxs/yT/MetHVi9zfXbp4Ctbd69I65/apZtr8vJzfLt78CIjtCTguFfKKAENTwPaOmJA7hlny1wPjBsjvV9v7AgdrE33obAV/DPm9oY48i8RsPvxsSaU7MV2Y6IqAqTTXMJ1+ZyEQLI4W4U4qedw5Yb3tRe5TKsDzDiq9IMcYJnOhX2GKtGoYD2pqbr/5BRUg3oH9zC8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
